import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'firebase_options.dart';
import 'screens/login_screen.dart';
import 'screens/dashboard_screen.dart';

/// Entry point of the Us Two app - a couple's menstruation sync app.
/// 
/// This app uses Firebase for backend services:
/// - Firebase Auth: For anonymous authentication
/// - Cloud Firestore: To store couple connection codes
/// - shared_preferences: For local persistence of the couple code
void main() async {
  // Ensure Flutter bindings are initialized before using platform channels
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase with the options generated by FlutterFire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Sign in anonymously automatically on app start
  await _signInAnonymously();
  
  // Check if user has already connected (has a saved couple code)
  final prefs = await SharedPreferences.getInstance();
  final savedCoupleCode = prefs.getString('couple_code');
  
  runApp(UsTwoApp(initialCoupleCode: savedCoupleCode));
}

/// Signs in the user anonymously using Firebase Auth.
Future<void> _signInAnonymously() async {
  try {
    final userCredential = await FirebaseAuth.instance.signInAnonymously();
    debugPrint('Signed in anonymously as: ${userCredential.user?.uid}');
  } on FirebaseAuthException catch (e) {
    debugPrint('Anonymous sign-in failed: ${e.message}');
  }
}

/// Root widget of the Us Two application.
class UsTwoApp extends StatelessWidget {
  final String? initialCoupleCode;
  
  const UsTwoApp({super.key, this.initialCoupleCode});

  // Light Turquoise color palette
  static const Color primaryTurquoise = Color(0xFF40E0D0); // Main turquoise
  static const Color lightTurquoise = Color(0xFF7FFFD4);   // Aquamarine
  static const Color darkTurquoise = Color(0xFF00CED1);    // Dark turquoise
  static const Color mintCream = Color(0xFFF5FFFA);        // Very light mint
  static const Color tealAccent = Color(0xFF64FFDA);       // Bright teal

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Us Two',
      debugShowCheckedModeBanner: false,
      
      // Beautiful LIGHT theme with turquoise accents
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        
        // Light mint background
        scaffoldBackgroundColor: mintCream,
        
        // Color scheme with turquoise tones
        colorScheme: ColorScheme.light(
          primary: primaryTurquoise,
          secondary: lightTurquoise,
          tertiary: tealAccent,
          surface: Colors.white,
          surfaceContainerHighest: const Color(0xFFE0F7F7),
          error: const Color(0xFFE57373),
          onPrimary: Colors.white,
          onSecondary: const Color(0xFF004D4D),
          onSurface: const Color(0xFF1A3A3A),
        ),
        
        // Card theme for elevated surfaces
        cardTheme: CardThemeData(
          color: Colors.white,
          elevation: 4,
          shadowColor: primaryTurquoise.withOpacity(0.2),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
        ),
        
        // App bar theme
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.transparent,
          elevation: 0,
          iconTheme: IconThemeData(color: Color(0xFF1A3A3A)),
          titleTextStyle: TextStyle(
            color: Color(0xFF1A3A3A),
            fontSize: 20,
            fontWeight: FontWeight.w600,
          ),
        ),
        
        // Elevated button styling
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: primaryTurquoise,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
            elevation: 4,
            shadowColor: primaryTurquoise.withOpacity(0.4),
          ),
        ),
        
        // Input decoration for text fields
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: Colors.white,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(color: primaryTurquoise.withOpacity(0.3)),
      ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(color: primaryTurquoise.withOpacity(0.3)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: const BorderSide(color: primaryTurquoise, width: 2),
          ),
          contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 18),
        ),
      ),
      
      // Start with Dashboard if already connected, otherwise show Login
      home: initialCoupleCode != null 
          ? DashboardScreen(coupleCode: initialCoupleCode!)
          : const LoginScreen(),
    );
  }
}
